language: python
python: "3.3"

install:
  - pip install flake8
  - pip install autopep8
  - pip install nose
  - pip install coverage
  - pip install hypothesis
  - pip install pycontracts
script:
  - python3 -m pip install -U mypy
  - python -m compileall .
  - python -m doctest python_lab_2.py --max-complexity=2
  - nosetests --cover-min-percentage=99 python_lab_2.py
